// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package com.fastaccess.data.dao.model;

import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;
import javax.annotation.Generated;

@Generated("io.requery.processor.EntityProcessor")
public class Models {
    public static final EntityModel DEFAULT = new EntityModelBuilder("default")
    .addType(Comment.$TYPE)
    .addType(Commit.$TYPE)
    .addType(Event.$TYPE)
    .addType(FastHubNotification.$TYPE)
    .addType(Gist.$TYPE)
    .addType(Issue.$TYPE)
    .addType(IssueEvent.$TYPE)
    .addType(Login.$TYPE)
    .addType(Notification.$TYPE)
    .addType(NotificationQueue.$TYPE)
    .addType(PinnedGists.$TYPE)
    .addType(PinnedIssues.$TYPE)
    .addType(PinnedPullRequests.$TYPE)
    .addType(PinnedRepos.$TYPE)
    .addType(PullRequest.$TYPE)
    .addType(Release.$TYPE)
    .addType(Repo.$TYPE)
    .addType(RepoFile.$TYPE)
    .addType(SearchHistory.$TYPE)
    .addType(User.$TYPE)
    .addType(ViewerFile.$TYPE)
    .build();

    private Models() {
    }
}
